#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 1          # you'll never need more than 1 node for the serial code
#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J serial
#SBATCH -o serial.%j.stdout
#SBATCH -e serial.%j.error

srun -n 1 -c 1 ./serial -n 4000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 4000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 4000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 8000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 8000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 8000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 12000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 12000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 12000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 24000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 24000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 36000 -no -o serial.txt
srun -n 1 -c 1 ./serial -n 36000 -no -o serial.txt
